# Generated by Django 2.0.9 on 2018-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_remove_servers_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='name',
        ),
        migrations.AddField(
            model_name='servers',
            name='listen_ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='servers',
            name='listen_port',
            field=models.IntegerField(default=1194),
        ),
        migrations.AddField(
            model_name='servers',
            name='path',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='servers',
            name='service_name',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
