# Generated by Django 2.0.9 on 2018-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20181125_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='OpenVPN', max_length=200)),
                ('listen_ip', models.CharField(default='0.0.0.0', max_length=20)),
                ('listen_port', models.IntegerField(default=1194)),
                ('path', models.CharField(default='-', max_length=200)),
                ('service_name', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
    ]
