# Generated by Django 2.1.7 on 2019-02-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
